### ISSUE TITLE
大神你好，问个问题，这个项目直接跑的话调用的是远程接口无token会直接跳转到登录页

### ISSUE THREAD

**Issue by xiongzhaoxu** [zhangyuanlj/approvalflow#1]
大神你好，问个问题，这个项目直接跑的话调用的是远程接口无token会直接跳转到登录页

**Comment by zhangyuanlj** [comment]
Hi xiongzhaoxu 
     你好！感谢你对本开源项目的关注，目前已将生产环境的接口地址修改为开发环境的接口地址，更新代码后项目就可跑起来，感谢你的支持！
